### ISSUE TITLE
Question About Tracking Data Processing for V2V4Real

### ISSUE THREAD

**Issue by katieluo88** [eddyhkchiu/DMSTrack#1]
Hi! Thanks for the amazing work; I noticed that you have some preprocessing step to get the tracks for the V2V4Real dataset at `v2v4real_[train/val]_evaluate_tracking.seqmap.val`. I was wondering how this is generated? Do you have the scripts to create these files, and the preprocessing for the label file?

In addition, I was wondering about the KITTI format labels in `AB3DMOT/scripts/KITTI/v2v4real_[train/val]_label`. Do you have a script to convert this for the v2v4real dataset? I presume that the track ID is the "Vehicle" index of v2v4real dataset annotation yaml file?

Thank you in advance for the clarifications!

**Comment by eddyhkchiu** [comment]
Hi Katie, 

Thanks for your interests in our paper!

I modified the v2v4real cooperative detection inference code to transform the v2v4real's detection output data and ground-truth label data into the KITTI format.

The entry point of my relevant code can be found in https://github.com/eddyhkchiu/DMSTrack/blob/master/V2V4Real/opencood/tools/inference.py#L395 .

If you want to transform the v2v4real's val split label data into KITTI format again, you can run my cobevt's val split cooperative detection inference by:
```shell
cd V2V4Real
python opencood/tools/inference.py --model_dir official_models/cobevt/ --fusion_method 'intermediate' --save_npy
```

Then you can find the v2v4real's val split ground-truth label data in KITTI format at 
```shell
V2V4Real/official_models/cobevt/npy/ab3dmot_tracking_label/*.txt
```

Those *.txt should be the same as the *.txt in
```shell
AB3DMOT/scripts/KITTI/v2v4real_val_label/*.txt
```

You can also copy those *.txt from the V2V4Real path to the AB3DMOT path. My tracking code uses the label files in the AB3DMOT path.

For the v2v4real's training split label data, you can follow the similar approach:
```shell
cd V2V4Real
mkdir official_models/train_cobevt/
cp official_models/cobevt/config.yaml official_models/train_cobevt/
cp official_models/cobevt/net_epoch60.pth official_models/train_cobevt/
```

Then, update the training split config file ```official_models/train_cobevt/config.yaml``` by
replacing ```validate_dir: './data/test'``` with ```validate_dir: './data/train'``` .

Then run the cobevt cooperative detection inference on the training split:
```shell
cd V2V4Real
python opencood/tools/inference.py --model_dir official_models/train_cobevt/ --fusion_method 'intermediate' --save_npy
```

Then you can find the v2v4real's training split ground-truth label data in KITTI format at 
```shell
V2V4Real/official_models/train_cobevt/npy/ab3dmot_tracking_label/*.txt
```

Those *.txt should be the same as the *.txt in
```shell
AB3DMOT/scripts/KITTI/v2v4real_train_label/*.txt
```


For your first question, the two files ```v2v4real_[train/val]_evaluate_tracking.seqmap.val``` just contain the information about how many frames are in each driving sequence. My cobevt cooperative detection inference code will print out such information, and I created those two files manually.


For your last question about the track ID, the answer is no.
In V2V4Real dataset, there are two vehicles with sensors. Each vehicle has its own label annotation yaml file. For example, in the first frame of the first driving sequence of validation split, CAV_0's annotation yaml file has one object with id 1, and CAV_1's annotation yaml file has one object with id 7.  When v2v4real generates the ground-truth object id, it will add 100 to CAV_1's object id. So for this frame, the ground-truth object ids are 1 and 107. The relevant code can be found in https://github.com/ucla-mobility/V2V4Real/blob/main/opencood/data_utils/post_processor/base_postprocessor.py#L153 . I follow this convention to generate my v2v4real's label data in KITTI format.

Let me know if you have any other questions.
Thanks!

**Comment by longlonglonghouhouhou** [comment]
Thank you for your work! Regarding the  results of 3d objection, in the ab3dmot format, x is right, but you did not process x, so x is forward. This confuses me.
in AB3DMOT/data/KITTI/detection/pointrcnn_Car_test/0000.txt
0,2,486.1155,176.2702,651.5070,239.1888,12.2642,1.5824,1.6535,4.1805,-1.0904,1.6770,19.0629,-0.0009,0.0562
but in AB3DMOT/data/v2v4real/detection/cobevt_Car_val/0000.txt
0,2,0,0,0,0,0.583378,1.6957035,2.034256,4.1307445,-20.65096,-1.1906503,-0.14174843,0.02093774,0.000000
z = 0.02093774,this is unreasonable

**Comment by longlonglonghouhouhou** [comment]
Thanks for following along! For the conversion part of the code. I still have some doubts .In AB3dMOT format，The reference frame is such that z points forward, y down, x right.But in opencood/tools/inference.py,only  y and  z are swaped.
For example，in /home/wql/DMSTrack/AB3DMOT/data/v2v4real/detection/cobevt_Car_val/0000.txt 
first line
0,2,0,0,0,0,0.583378,1.6957035,2.034256,4.1307445,-20.65096,-1.1906503,-0.14174843,0.02093774,0.000000
z = -0.14174843，this means that the target vehicle is 0.14m behind the center of ego.
Hope to get your reply.

**Comment by eddyhkchiu** [comment]
Thanks for your question.
I did not fully follow the ab3dmot kitti coordinate system convention.

As you mentioned, the regular ab3dmot kitti coordinate system is:
Right-hand coordinate system, 
x: right, y: down, z: forward
theta: rotation around y-axis

The v2v4real coordinate system is:
Left-hand coordinate system,
x: forward, y: right, z: up
theta: rotation around z-axis

And my transformation code's output data are in the following coordinate system:
Right-hand coordinate system, 
x: forward, y: up, z: right
theta: rotation around y-axis

And my transformed label data and detection data are stored in this coordinate system. Although this coordinate system is different from the regular ab3dmot kitti coordinate system convention, that does not affect the tracking AMOTA evaluation, 3D IOU calculation, and Kalman Filter tracking. As long as the detection boxes and gt label boxes are stored in the same coordinate system, the evaluation result will be the same.

Back to your example, that means cobevt cooperative detection model generates a detection result box, whose relative position to the ego car is  x = -20.65096, y = -1.1906503, z = -0.14174843 in my coordinate system. This detection result box is behind the ego car by 20 meters, which is near the locations of red and magenta boxes in the middle of this figure:

![github_question](https://github.com/eddyhkchiu/DMSTrack/assets/30642642/8cd0b26a-1ff3-4b2a-9f78-8686871b4b85)
