### ISSUE TITLE
Does the detection result data include a confidence value?

### ISSUE THREAD

**Issue by yhl3030** [eddyhkchiu/DMSTrack#2]
The data in "DMSTrack/AB3DMOT/data/v2v4real/detection/multi_sensor_differentiable_kalman_filter_Car_train/1/0000.txt" consists of the following values:
0, 2, 0, 0, 0, 0, 0.619345, 1.663162, 1.8595805, 4.197101, -20.90078, 0.3129107, 1.1157186, -0.07246299, 0.000000.
Does the seventh value represent the confidence level?

**Comment by eddyhkchiu** [comment]
Hi,

Yes, the seventh value represents the detection confidence score.
We follow AB3DMOT's 3D object detection format in https://github.com/xinshuoweng/AB3DMOT/blob/master/docs/KITTI.md

**Comment by yhl3030** [comment]
Thank you for your response
