### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by txy00001** [eddyhkchiu/DMSTrack#3]
Hello, very good job, how long does it take to reason? I wonder how this model infers a custom dataset? And how do you convert it to onnx or tensorrt for deployment? Looking forward to your answers? Can this be combined with bevfusion?

**Comment by txy00001** [comment]
![image](https://github.com/user-attachments/assets/f9d6441e-c50b-4488-bc86-6b2aefaaa18a)
Run python opencood/utils/setup.py build_ext --inplace and get an error? How do I fix this?

**Comment by eddyhkchiu** [comment]
Hi, 

Thanks for your interests in our work!

In terms of inference time including 3D object detection and tracking, the current FPS is roughly 4.
The majority run time is used in data association's 3D IOU calculation, where we reuse AB3DMOT's code. Its implementation uses a nested for loop over all pairs of detection results in the current frame and the previous frame. That can be further optimized for faster inference. When using center distances for data association, the FPS is roughly 10.

For custom datasets and onnx/tensorrt deployment, I have not tried those things before.

Yes, I think our work can be combined with bevfusion. You can replace our model's PointPillars 3D object detector with the bevfusion model, and then apply the differentiable Kalman Filter for tracking.
